on projectile launch:
    set {_world} to name of world of shooter
    if {_world} is "spawn":
        if projectile is a wind charge:
            cancel event
            send action bar "§x§F§F§3§4§0§0You cannot use Wind Charges in this world." to shooter
        if projectile is an ender pearl:
            cancel event
            send action bar "§x§F§F§3§4§0§0You cannot use Ender Pearls in this world." to shooter
